// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`.

// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports

import 'dart:convert';
import 'dart:typed_data';

import 'dart:convert';
import 'dart:typed_data';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'dart:ffi' as ffi;

abstract class ApiOrder {
  Future<List<OrderItem>> getOrders(
      {required int offset, required int limit, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kGetOrdersConstMeta;

  Future<void> writeFile(
      {required String filepath, required String content, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kWriteFileConstMeta;

  Future<String> readFile({required String filepath, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kReadFileConstMeta;
}

class OrderItem {
  final int id;
  final String title;

  OrderItem({
    required this.id,
    required this.title,
  });
}

class ApiOrderImpl extends FlutterRustBridgeBase<ApiOrderWire>
    implements ApiOrder {
  factory ApiOrderImpl(ffi.DynamicLibrary dylib) =>
      ApiOrderImpl.raw(ApiOrderWire(dylib));

  ApiOrderImpl.raw(ApiOrderWire inner) : super(inner);

  Future<List<OrderItem>> getOrders(
          {required int offset, required int limit, dynamic hint}) =>
      executeNormal(FlutterRustBridgeTask(
        callFfi: (port_) => inner.wire_get_orders(
            port_, _api2wire_i32(offset), _api2wire_i32(limit)),
        parseSuccessData: _wire2api_list_order_item,
        constMeta: kGetOrdersConstMeta,
        argValues: [offset, limit],
        hint: hint,
      ));

  FlutterRustBridgeTaskConstMeta get kGetOrdersConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "get_orders",
        argNames: ["offset", "limit"],
      );

  Future<void> writeFile(
          {required String filepath, required String content, dynamic hint}) =>
      executeNormal(FlutterRustBridgeTask(
        callFfi: (port_) => inner.wire_write_file(
            port_, _api2wire_String(filepath), _api2wire_String(content)),
        parseSuccessData: _wire2api_unit,
        constMeta: kWriteFileConstMeta,
        argValues: [filepath, content],
        hint: hint,
      ));

  FlutterRustBridgeTaskConstMeta get kWriteFileConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "write_file",
        argNames: ["filepath", "content"],
      );

  Future<String> readFile({required String filepath, dynamic hint}) =>
      executeNormal(FlutterRustBridgeTask(
        callFfi: (port_) =>
            inner.wire_read_file(port_, _api2wire_String(filepath)),
        parseSuccessData: _wire2api_String,
        constMeta: kReadFileConstMeta,
        argValues: [filepath],
        hint: hint,
      ));

  FlutterRustBridgeTaskConstMeta get kReadFileConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "read_file",
        argNames: ["filepath"],
      );

  // Section: api2wire
  ffi.Pointer<wire_uint_8_list> _api2wire_String(String raw) {
    return _api2wire_uint_8_list(utf8.encoder.convert(raw));
  }

  int _api2wire_i32(int raw) {
    return raw;
  }

  int _api2wire_u8(int raw) {
    return raw;
  }

  ffi.Pointer<wire_uint_8_list> _api2wire_uint_8_list(Uint8List raw) {
    final ans = inner.new_uint_8_list_0(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

  // Section: api_fill_to_wire

}

// Section: wire2api
String _wire2api_String(dynamic raw) {
  return raw as String;
}

int _wire2api_i32(dynamic raw) {
  return raw as int;
}

List<OrderItem> _wire2api_list_order_item(dynamic raw) {
  return (raw as List<dynamic>).map(_wire2api_order_item).toList();
}

OrderItem _wire2api_order_item(dynamic raw) {
  final arr = raw as List<dynamic>;
  if (arr.length != 2)
    throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
  return OrderItem(
    id: _wire2api_i32(arr[0]),
    title: _wire2api_String(arr[1]),
  );
}

int _wire2api_u8(dynamic raw) {
  return raw as int;
}

Uint8List _wire2api_uint_8_list(dynamic raw) {
  return raw as Uint8List;
}

void _wire2api_unit(dynamic raw) {
  return;
}

// ignore_for_file: camel_case_types, non_constant_identifier_names, avoid_positional_boolean_parameters, annotate_overrides, constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.

/// generated by flutter_rust_bridge
class ApiOrderWire implements FlutterRustBridgeWireBase {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  ApiOrderWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  ApiOrderWire.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  void wire_get_orders(
    int port_,
    int offset,
    int limit,
  ) {
    return _wire_get_orders(
      port_,
      offset,
      limit,
    );
  }

  late final _wire_get_ordersPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Int64, ffi.Int32, ffi.Int32)>>('wire_get_orders');
  late final _wire_get_orders =
      _wire_get_ordersPtr.asFunction<void Function(int, int, int)>();

  void wire_write_file(
    int port_,
    ffi.Pointer<wire_uint_8_list> filepath,
    ffi.Pointer<wire_uint_8_list> content,
  ) {
    return _wire_write_file(
      port_,
      filepath,
      content,
    );
  }

  late final _wire_write_filePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Int64, ffi.Pointer<wire_uint_8_list>,
              ffi.Pointer<wire_uint_8_list>)>>('wire_write_file');
  late final _wire_write_file = _wire_write_filePtr.asFunction<
      void Function(
          int, ffi.Pointer<wire_uint_8_list>, ffi.Pointer<wire_uint_8_list>)>();

  void wire_read_file(
    int port_,
    ffi.Pointer<wire_uint_8_list> filepath,
  ) {
    return _wire_read_file(
      port_,
      filepath,
    );
  }

  late final _wire_read_filePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Int64, ffi.Pointer<wire_uint_8_list>)>>('wire_read_file');
  late final _wire_read_file = _wire_read_filePtr
      .asFunction<void Function(int, ffi.Pointer<wire_uint_8_list>)>();

  ffi.Pointer<wire_uint_8_list> new_uint_8_list_0(
    int len,
  ) {
    return _new_uint_8_list_0(
      len,
    );
  }

  late final _new_uint_8_list_0Ptr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<wire_uint_8_list> Function(
              ffi.Int32)>>('new_uint_8_list_0');
  late final _new_uint_8_list_0 = _new_uint_8_list_0Ptr
      .asFunction<ffi.Pointer<wire_uint_8_list> Function(int)>();

  void free_WireSyncReturnStruct(
    WireSyncReturnStruct val,
  ) {
    return _free_WireSyncReturnStruct(
      val,
    );
  }

  late final _free_WireSyncReturnStructPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(WireSyncReturnStruct)>>(
          'free_WireSyncReturnStruct');
  late final _free_WireSyncReturnStruct = _free_WireSyncReturnStructPtr
      .asFunction<void Function(WireSyncReturnStruct)>();

  void store_dart_post_cobject(
    DartPostCObjectFnType ptr,
  ) {
    return _store_dart_post_cobject(
      ptr,
    );
  }

  late final _store_dart_post_cobjectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(DartPostCObjectFnType)>>(
          'store_dart_post_cobject');
  late final _store_dart_post_cobject = _store_dart_post_cobjectPtr
      .asFunction<void Function(DartPostCObjectFnType)>();
}

class wire_uint_8_list extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Int32()
  external int len;
}

typedef DartPostCObjectFnType = ffi.Pointer<
    ffi.NativeFunction<ffi.Bool Function(DartPort, ffi.Pointer<ffi.Void>)>>;
typedef DartPort = ffi.Int64;
